# Creation date : 18.03.2024
# Created by : CSR
# Description : This compose file creates a stack of two containers (nodejs + mysql)
#version: "2"

# Updated date : 27.05.2024
# Updated by : ALO
# Description : This docker compose creates a stack of 3 contaainers (nodejs + vuejs + mysql)

version: '3.8'
services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: etml
      MYSQL_PASSWORD: etml
      MYSQL_DATABASE: db_esn_social_network
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.0
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

  nodejs:
    build:
      context: ./app
      dockerfile: nodejs.dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules
    expose:
      - "443"
    ports:
      - "443:443"
    command: "npm start"

  python:
    build:
      context: ./algo
      dockerfile: python.dockerfile
    depends_on:
      - db
      - nodejs
    command: "python3 script.py"

volumes:
  dbdata:
