version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    build:
      context: ./pma
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    restart: always
    ports:
      - 8081:80
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000'
  algo:
    build:
      context: ./algo
      dockerfile: Dockerfile
    depends_on:
      - db
      - backend
volumes:
  db-data:
networks:
  default: